---
title: "zero inflated data"
author: "Danielle Zhang"
date: "15/02/2018"
output: html_document
---
```{r}
library(tidyverse)
library(gamlss)
x = read_csv("data/lot_data.csv.gz",guess_max = 100000) %>% 
  filter(-msaindex_mean,-msaindex_sd,ph_mean,ph_sd, -meatcolour_mean,meatcolour_sd)

glimpse(x)
```

```{r}
plot(table(x$dfd_perc))
x$dfd_perc[x$dfd_perc==1] = 0.99 #UGLY!
xsub = x %>% dplyr::select(dfd_perc,producer,hump_mean ,
                             sex_mf , hgp_mf ,fatcolour_mean) %>% 
  na.omit()

xsub %>% mutate(dfd_perc_2 = ifelse(dfd_perc != 0, 1, 0)) %>% 
  group_by(producer, dfd_perc_2) %>% summarise(n = n()) %>% filter(dfd_perc_2 == 1)
```

```{r}
m1 = gamlss(dfd_perc ~ producer + hump_mean + 
              sex_mf + hgp_mf + fatcolour_mean - 1, family = BEZI, data = xsub, trace = FALSE)
summary(m1)
```


```{r}
m2 = gamlss(dfd_perc ~ producer + 
              sex_mf + hgp_mf + fatcolour_mean - 1, family = BEZI, data = xsub, trace = FALSE)
summary(m2)
```

Can we compare `m1` and `m2`? (Garth) needs to look into this more.


```{r}
ggplot(data = xsub %>% filter(producer == "Prime City")) +
  geom_bar(mapping = aes(x = dfd_perc))

m3 = gamlss(dfd_perc ~ sex_mf + fatcolour_mean + hump_mean - 1, family = BEZI, data = xsub %>% filter(producer == "Prime City"), trace = FALSE)
summary(m3)

xsub %>% filter(dfd_perc == 0) %>% group_by(hgp_mf) %>% summarise(n = n())
```

```{r}
m4 = gamlss(dfd_perc ~ producer - 1, family = BEZI, data = xsub, trace = FALSE)
summary(m4)
```

```{r}
m5 = gamlss(dfd_perc ~ sex_mf + fatcolour_mean + hgp_mf - 1, famiy = BEZI, data = xsub, trace = FALSE)
summary(m5)
```

```{r}
m6 = gamlss(dfd_perc ~ sex_mf + fatcolour_mean + hgp_mf + hump_mean -1, family = BEZI, 
            data = xsub %>% filter(producer == "Condamine"), trace = F)
summary(m6)
```

```{r}
m7 = gamlss(dfd_perc ~ sex_mf + fatcolour_mean + hgp_mf + hump_mean -1, family = BEZI, 
            data = xsub %>% filter(producer == "Myola"), trace = F)
summary(m7)
```

```{r}
m8 = gamlss(dfd_perc ~ producer + sex_mf + fatcolour_mean + hgp_mf + hump_mean -1, family = BE, 
            data = xsub %>% filter(dfd_perc != 0), trace = F)
summary(m8)
```
 